### ISSUE TITLE
Several dialog types are not working with QGnomePlatform

### ISSUE THREAD

**Issue by Venemo** [MartinBriza/QGnomePlatform#10]
I'm using Qt 5.6.1-3.fc24.x86_64 from Fedora 24 on Gnome 3. Several of the dialog types are not working at all. The easiest way to reproduce this is to use the `systemdialogs` example in Qt Creator.

When using QGnomePlatform,

* `FileDialog` shows something weird, definitely not the native Gnome file dialog
* `ColorDialog`, `FontDialog` and `MessageDialog` do not work **at all**
* Custom `Dialog` works as expected.

When **not** using QGnomePlatform,

* `FileDialog` shows the native Gnome file dialog
* `ColorDialog`, `FontDialog` and `MessageDialog` **do not show** the Gnome dialog, but at least work
* Custom `Dialog` looks identical to the app with QGnomePlatform

**Comment by grulja** [comment]
Fixed by https://github.com/MartinBriza/QGnomePlatform/commit/e13a9596e3714f5ecbe1ab00fcc89f1a5bf25a62
