### ISSUE TITLE
Add support for other styles [patch]

### ISSUE THREAD

**Issue by polter-rnd** [MartinBriza/QGnomePlatform#18]
I've forked your **adwaita-qt** project to make Qt version of style adwaita-compact: [adwaita-compact-qt](https://github.com/polter-rnd/adwaita-compact-qt).

The problem is that it doesn't work with QGnomePlatform because it has a fixed list with styles. I've patched it this way:
```
--- src/gnomehintssettings.cpp.orig	2017-01-02 17:00:40.955909108 +0300
+++ src/gnomehintssettings.cpp	2017-01-02 17:03:28.084595516 +0300
@@ -116,8 +116,11 @@
     m_hints[QPlatformTheme::SystemIconFallbackThemeName] = "breeze";
     m_hints[QPlatformTheme::IconThemeSearchPaths] = xdgIconThemePaths();
 
+    // First try to use GTK theme if it's Qt version is available
+    // Otherwise, use adwaita or try default themes
     QStringList styleNames;
-    styleNames << QStringLiteral("adwaita")
+    styleNames << m_gtkTheme
+               << QStringLiteral("adwaita")
                // Avoid using gtk+ style as it uses gtk2 and we use gtk3 which is causing a crash
                // << QStringLiteral("gtk+")
                << QStringLiteral("fusion")
```

How about adding something like this to upstream? It will help integrating Qt apps with GNOME since not everybody use Adwaita.

**Comment by MartinBriza** [comment]
Hello, thanks for the patch! I just noticed the GTK theme is not utilized by default today when writing the highcontrast theme. I'll fix this in the following days.

**Comment by MartinBriza** [comment]
Yup, it works alright this way, sorry for not including it by default.
Since it's your patch, if you want to be attributed properly, can you please submit it as a pull request?

**Comment by polter-rnd** [comment]
Done, thanks for responsiveness!

**Comment by MartinBriza** [comment]
Thanks for the patch!
