### ISSUE TITLE
It does not use dark theme when it was enabled

### ISSUE THREAD

**Issue by RenaultR42** [MartinBriza/QGnomePlatform#2]
With Gnome, I use the dark theme of Adwaita by the global option with gnome-tweak-tool.
So, I tested liveusb-creator, Qt application which use your work normally (the theme is closer to real GTK application) but the theme still in white...

Do you plan to take account that option?

**Comment by RenaultR42** [comment]
Screenshot of "trouble"

![virtualbox_fedora24_15_03_2016_17_29_10](https://cloud.githubusercontent.com/assets/12804924/13785648/94e88484-ead4-11e5-9f40-f5747aca76f9.png)

Note that interface bug with dark theme, I don't have trouble with white theme.

**Comment by MartinBriza** [comment]
Hello,
sorry for taking so long to answer, I sort of forgot to reply to this report. This is a problem of the application you're using (it utilizes the colors in a wrong way). You're also using a deprecated application. Fedora LiveUSB Creator was superseded by the Fedora Media Writer (mediawriter package in Fedora) which has a lot new features, is more stable and it also handles dark themes correctly. 
I'll close this issue but please keep in touch in case of any other questions, concerns or bug reports.
