### ISSUE TITLE
QObject::connect: invalid null parameter for native dialogs without parent

### ISSUE THREAD

**Issue by rokm** [MartinBriza/QGnomePlatform#31]
Running a (native) dialog without parent results in the following warning printed to the terminal:
> QObject::connect: invalid null parameter

Judging by the message, the most likely cause is a connect() call on the (null) parent object.

MWE:
```C++
#include <QtWidgets>

int main (int argc, char **argv)
{
    QApplication app(argc, argv);
    QFileDialog::getOpenFileName();
    return 0;
}
```

**Comment by grulja** [comment]
Fixed by https://github.com/MartinBriza/QGnomePlatform/pull/32.
