### ISSUE TITLE
Changing the appearance of qt apps

### ISSUE THREAD

**Issue by light2yellow** [MartinBriza/QGnomePlatform#7]
How could I generally affect qt look? For example, using goldendict the interface renders in gtk+ style and looks ok, but using okular the interface is pretty ugly with italic fonts and dumb icons. 'qgnomeplatform' is exported.

**Comment by grulja** [comment]
Do you have adwaita-qt theme installed?

**Comment by light2yellow** [comment]
I've just installed it and restarted X session. Goldendict looks uglier than before and okular still uses bold italics, although the background has changed from gray to white. So, adwaita is the only one theme currently available? How do I keep this theme on my pc and stick to defaults?

**Comment by grulja** [comment]
Please provide a screenshot. Adwaita is the default theme used when it's available, gtk+ theme is ignored as it causes some problems. If adwaita-qt is not available then fusion theme is used.

**Comment by light2yellow** [comment]
Read adwaita-qt's README and configured the font in qtconfig-qt4. Still not perfect, but much better than before. I'm going to experiment with different setups, thanks for your help.
