### ISSUE TITLE
Missing native dialogs

### ISSUE THREAD

**Issue by rokm** [MartinBriza/QGnomePlatform#9]
With QGnomePlatform enabled, whenever the application requests a file chooser dialog, a color chooser dialog, or a font chooser dialog, the Qt-provided dialogs are used, which are lacking both in aesthetics and in functionality. To the end-user, this will look like an obvious regression compared to Gtk2-dialogs provided by QGtk2 platform theme, which is used by default in absence of QGnomePlatform.

The reason is that QGtk2 provides wrappers for the native dialogs, which are missing from the QGnomePlatform. In Qt 5.7, QGtk2 was replaced by QGtk3 theme platform, which provides wrappers for Gtk3 dialogs. That code could be directly integrated into QGnomePlatform to provide the missing dialog functionality, or could serve as a good starting point for reimplementation.

**Comment by grulja** [comment]
Native dialogs already merged in master.
